### ISSUE TITLE
Piping data into 'run' command 

### ISSUE THREAD

**Issue by Nilix007** [appc/acbuild#200]
Hey,

I think it's useful to let people pipe data into commands which are run with the subcommand 'run' in the ACI. So, for example, I use this for running complex install scripts inside the ACI with
```
$ acbuild run sh <<EOF
command1
command2
...
EOF
```

PS: I've managed to enable this feature with the following quick and dirty patch:
(which might have some unwanted side-effects elsewhere)
```
diff --git a/engine/systemdnspawn/systemdnspawn.go b/engine/systemdnspawn/systemdnspawn.go
index bd000f9..e249c55 100644
--- a/engine/systemdnspawn/systemdnspawn.go
+++ b/engine/systemdnspawn/systemdnspawn.go
@@ -75,6 +75,7 @@ func (e Engine) Run(command string, args []string, environment types.Environment
 	nspawncmd = append(nspawncmd, args...)
 
 	execCmd := exec.Command(nspawncmd[0], nspawncmd[1:]...)
+	execCmd.Stdin = os.Stdin
 	execCmd.Stdout = os.Stdout
 	execCmd.Stderr = os.Stderr
 	execCmd.Env = []string{"SYSTEMD_LOG_LEVEL=err"}
```

**Comment by jonboulle** [comment]
Seems pretty reasonable, we could probably accept a patch like that!

**Comment by dgonyeo** [comment]
I've been debating whether or not to attach stdin since writing the `run` command. This seems generally useful. My initial thought was that maybe hide this behind a flag, but my second thought is that I can't think of anything that adding this would break, so let's just add the line as-is.

@Nilix007 want to make a PR for this, or do you just want me to make the changes?

**Comment by dgonyeo** [comment]
https://github.com/appc/acbuild/pull/224
