### ISSUE TITLE
Error using acbuild run with Ubuntu 14.04

### ISSUE THREAD

**Issue by foxx** [appc/acbuild#216]
```
$ acbuild --debug run apk update
run: overlayfs is not supported on your system

$ lsmod | grep overlay
overlayfs              28027  0
```

Seems to be related to this [line](https://github.com/appc/acbuild/blob/master/lib/run.go#L99):

```
err := exec.Command("modprobe", "overlay").Run()
```

**Comment by iaguis** [comment]
The kernel changed the name from `overlayfs` to `overlay` when it was fully implemented, so `overlayfs != overlay`.

Ref: https://github.com/docker/docker/issues/10353

**Comment by foxx** [comment]
Oh dang, so I'd need to be running `16.04` in order to fix this? Thanks for the heads up, closing out!

**Comment by iaguis** [comment]
You need a >3.18 kernel.

Is falling back to copying files if overlay is not supported feasible? @dgonyeo

**Comment by dgonyeo** [comment]
Copying the files would only be feasible if we squash the image, since acbuild would then need to separate the files out into layers again after the run command. I have a very old issue for adding an `acbuild squash` (https://github.com/appc/acbuild/issues/18), if that were implemented it would at least provide a workaround for machines without overlay support.

I could also get acbuild to accept both `overlayfs` and `overlay` for the kernel module it tries to load, so that acbuild would work on older kernels. Thoughts @iaguis?

**Comment by foxx** [comment]
Fwiw I would normally be using `16.04` but currently there are bugs using it with `vagrant`, otherwise I'd just upgrade!
