### ISSUE TITLE
please update for appc/spec v0.8.5 API changes

### ISSUE THREAD

**Issue by onlyjob** [appc/acbuild#229]
_acbuild_ FTBFS with _appc/spec_ v0.8.5:

~~~~
# github.com/appc/acbuild/registry 
src/github.com/appc/acbuild/registry/fetch.go:339: not enough arguments in call to discovery.DiscoverACIEndpoints 
~~~~

**Comment by onlyjob** [comment]
All what's left to do is to tag new release?

**Comment by dgonyeo** [comment]
Yup. I'll make the PR today.

**Comment by onlyjob** [comment]
Ping? There were no new release tagged yet...

**Comment by onlyjob** [comment]
@jonboulle, @alban guys, we need new release tagged please...

**Comment by alban** [comment]
I don't think I can tag a new release on this repository.

@dgonyeo can you do a tag?

**Comment by dgonyeo** [comment]
@alban would you mind reviewing and LGTM'ing https://github.com/appc/acbuild/pull/240, https://github.com/appc/acbuild/pull/239, and https://github.com/appc/acbuild/pull/226 before I do another release?

There have been some new features merged since the last release so I don't want to do a minor release, and I was hoping to have these PRs in before v0.4.0.

cc @jonboulle

**Comment by onlyjob** [comment]
Another week passed yet acbuild remains broken... How are things with tagging new release?

**Comment by jonboulle** [comment]
I think @dgonyeo still wants to see #226 land.. hopefully this can happen when he wakes up :-)

**Comment by dgonyeo** [comment]
@onlyjob sorry about the delay, here's the release: https://github.com/appc/acbuild/releases/tag/v0.4.0

**Comment by onlyjob** [comment]
Thanks! :)
