### ISSUE TITLE
Current tar implementation requires begin to be run as root

### ISSUE THREAD

**Issue by dgonyeo** [appc/acbuild#35]
The ExpandTar function untars the ACI in a chroot, which requires root permissions to set up.

**Comment by jonboulle** [comment]
ah, thanks for reminding me about this, I was intending to file an issue. I
think we should be able to just split this out and use ExtractTarChroot iff
euid == 0, and ExtractTar otherwise?

**Comment by alban** [comment]
If a regular non-root user `bob` wants to build an ACI that contains files belonging to someone else than `bob`, the tar create/extract functions must be able to ignore the file ownership in the `.acbuild` directory, and instead `acbuild` must have a separate database of files' ownerships.

Basically this is what [FakeRoot](http://manpages.debian.org/cgi-bin/man.cgi?sektion=1&query=fakeroot&apropos=0&manpath=sid&locale=en) does but since we control the tar library from go, we don't need this kind of `LD_PRELOAD` trick.

The tar writer [BuildWalker](https://github.com/appc/spec/blob/master/aci/build.go#L98) used by [End](https://github.com/appc/acbuild/blob/master/lib/end.go#L68) already has a callback that can be used to change the files ownership in the tarball (added by https://github.com/appc/spec/issues/498). But for the tar reader part (extract), I don't know if rkt/pkg/tar (https://github.com/coreos/rkt/pull/1616) should grow this kind of feature or if it should be implemented directly in acbuild?

**Comment by alban** [comment]
Also, [ExpandTar](https://github.com/coreos/rkt/blob/master/pkg/tar/tar.go) can only extract to `/`: see how it is hardcoded: `filepath.Join("/", hdr.Name)`. This is ok for `rkt` but does not really fit `acbuild`'s requirements.

**Comment by jonboulle** [comment]
@alban my proposal [here](https://github.com/coreos/rkt/pull/1616#discussion_r42293265)

**Comment by jonboulle** [comment]
@dgonyeo is this done now?

**Comment by dgonyeo** [comment]
Nope, I still need to make a PR to make use of the new `ExtractTarInsecure` function. I'll get around to it in the near future.
