### ISSUE TITLE
*: initial implementation

### ISSUE THREAD

**Issue by jonboulle** [appc/acbuild#5]
The [README](https://github.com/appc/acbuild/blob/master/README.md) describes what acbuild should look like; now we need an initial implementation of the thing.

**Comment by sgotti** [comment]
@jonboulle Is someone (@klizhentas ?) already working on it?

**Comment by klizhentas** [comment]
we chatted with @derekchiang about hacking on this and outlined a simple plan, but haven't started yet. @sgotti you want to hack together?

**Comment by sgotti** [comment]
@klizhentas @derekchiang Good to know! Perhaps, due to other work in this week (I don't want to become a bottleneck) it'll be better if we can just put a basic initial implementation PR of some initial commands and then follow with the classic workflow opening various PR.

I'm open for helping and for every suggestion!

**Comment by klizhentas** [comment]
@sgotti agreed. We will come up with the initial implementation PR for the most important command - exec in the next couple of weeks, and we'll go from there.

**Comment by derekchiang** [comment]
Sounds good to me. I have been busy this week but I will start working on
it over this weekend.

**Comment by dgonyeo** [comment]
An initial implementation was just merged.
